version: '3'

services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=123456"
  kala:
    build: .
    image: eu.gcr.io/htz-common/kala:0.0.1
    ports:
      - "8000:8000"
    environment:
      - "JOBDB=mongo"
      - "JOBDB_ADDRESS=mongo"
      - "JOBDB_USERNAME=root"
      - "JOBDB_PASSWORD=123456"

    


